INSERT INTO resources (owner_id, category_id, title, url, description) VALUES
(1, 1, 'JAVASCRIPT', 'https://www.youtube.com/watch?v=PkZNo7MFNFg', 'This complete 134-part JavaScript tutorial for beginners will teach you everything you need to know to get started with the JavaScript programming language.'),
(2, 1, 'C++', 'https://www.youtube.com/watch?v=vLnPwxZdW4Y', 'This course will give you a full introduction into all of the core concepts in C++. '),
(3, 1, 'REACT', 'https://www.youtube.com/watch?v=w7ejDZ8SWv8&t=803s', 'Get started with React in this crash course. We will be building a task tracker app and look at components, props, state, hooks, working with an API and more.'),
(4, 1, 'TYPESCRIPT', 'https://www.youtube.com/watch?v=BwuLxPH8IDs', 'Free TypeScript Introduction for Beginners: Get Started with TypeScript, learn the Basics, its Features, Workflows and how to use it!'),
(5, 2, 'SALSA', 'https://www.youtube.com/watch?v=d8kxCB8GMt0', '22 SALSA CLASSICS HITS ► 1:55 hr VIDEO MIX COMPILATION ► GREATEST SALSA SONGS ► TODOS EXITOS ► SALSA PARA BAILAR, SALSA ROMANTICA, SALSA URBANA ► ALL ORIGINAL VIDEOS AND VERSIONS!'),
(6, 2, 'TANGO', 'https://www.youtube.com/watch?v=xAaPkOYiQWc', 'London Tango Festival 2011 took place at Porchester Hall Bayswater on 18th November 2011 with appearance of best champion tango dancers from all over the world. Watch this amazing video clip Recoded and produce by: Reza Kaz of kazzyandsally.tv'),
(7, 2, 'BALLET', 'https://www.youtube.com/watch?v=zV1qLYukTH8', 'Dance of the Sugar Plum Fairy from The Nutcracker (The Royal Ballet)'),
(8, 2, 'ZUMBA', 'https://www.youtube.com/watch?v=ymigWt5TOV8', 'This is my first ever Zumba kids group in Gargždai city and they are dancing only one '),
(9, 3, 'OMELETS', 'https://www.youtube.com/watch?v=i21vwKXtcaU', 'Want to know how to make the perfect omelet? Look no further'),
(10, 3,'Sausage Stew', 'https://www.youtube.com/watch?v=HuzOYHe3s0Y', 'Korean Sausage Stew l Army base stew l Budae-Jjigae '),
(11, 3, 'Black bean Noodles', 'https://www.youtube.com/watch?v=vHu2cmfXB3o', 'Today’s menu is jajangmyeon(Korean black bean noodles),as requested in the comments. Jajangmyeon is highly requested by my foreign subscribers. Maybe because of K-drama. Koreans make a point of ordering jajangmyeon delivery on the day move into a new home.'),
(12, 3, 'hot hamburger', 'https://www.youtube.com/watch?v=VsDtnTvgDB0', 'Sold out every day! The hamburger that won the 1st place in the US Best Burger Awards 3 times'),
(13, 4, 'FRENCH','https://www.youtube.com/watch?v=ujDtm0hZyII', 'Hurry! Click Here to Learn French with a BIG 29% Discount on all FrenchPod101'),
(14, 4, 'SPANISH', 'https://www.youtube.com/watch?v=qE-03EATjho', 'Learn Spanish in 4 Hours - ALL the Spanish Basics You Need'),
(15, 4, 'GERMAN', 'https://www.youtube.com/watch?v=xg60VxyK-9I', 'Learn German in 25 Minutes - ALL the Basics You Need'),
(17, 4, 'ENGLISH', 'https://www.youtube.com/watch?v=HV6h7MRrRNA', 'Do You Have 1 Hour? You Can Speak Like a Native English Speaker'),
(18, 5, 'SNOWBOARD', 'https://www.youtube.com/watch?v=t705_V-RDcQ', 'Bringing you 5 unique snow projects from the crazy world of snowboarding!'),
(19, 5, 'SKI', 'https://www.youtube.com/watch?v=g0FMrjsYAzc', 'GoPro: Tanner Hall Ski Diaries 2'),
(20, 5, 'SWIM', 'https://www.youtube.com/watch?v=LijdyVaaDnY', 'Smooth swimming step by step'),
(10, 5, 'SURFING', 'https://www.youtube.com/watch?v=ma67yOdMQfs', 'These Were The All-Time Surfing Moments Of The Year | Best Of 2020');
